version: '2'
services:
    chamados-app:
        image: chamados
        external_links:
            - chamados-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/chamados
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    chamados-postgresql:
        extends:
            file: postgresql.yml
            service: chamados-postgresql
