version: '2'
services:
    chamados-postgresql:
        container_name: chamados-postgresql
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/chamados/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=chamados
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
